#include <stdio.h>
#include "libftprintf.h"
#include <stdint.h>

int		main()
{
	int 		a;
	long int 	b;
	long long int c;
	int 		d;
	long long	int	e;
	ssize_t 		f;

	a = 1789;
	b = -2999900;
	c = -989849849452;
	d = 0;
	e = -9223372036854775808;
	f = -9223372036854775808;

/*	ft_printf("test de a pour d [%-10.6d]\n", a);
	ft_printf("test de a pour o [%o]\n", a);
	ft_printf("test de a pour u [%u]\n", a);
	ft_printf("test de a pour x [%x]\n", a);
	ft_printf("test de a pour X [%X]\n", a);
	ft_printf("test de b pour ld [%ld]\n", b);
	ft_printf("test de b pour lo [%lo]\n", b);
	ft_printf("test de b pour lu [%lu]\n", b);
	ft_printf("test de b pour lx [%lx]\n", b);
	ft_printf("test de b pour lX [%lX]\n", b);
	ft_printf("test de c pour lld [%lld]\n", c);
	ft_printf("test de c pour llo [%llo]\n", c);
	ft_printf("test de c pour llu [%llu]\n", c);
	ft_printf("test de c pour llx [%llx]\n", c);
	ft_printf("test de c pour llX [%llX]\n", c);
	ft_printf("test de a pour d [%d]\n");
	ft_printf("test de a pour o [%o]\n");
	ft_printf("test de a pour u [%u]\n");
	ft_printf("test de a pour x [%x]\n");
	ft_printf("test de a pour X [%X]\n");
	ft_printf("test de a pour d [%d]\n", a, b, c, a, c, b);
	ft_printf("test de a pour o [%o]\n", a, b);
	ft_printf("test de a pour u [%u]\n", a, b);
	ft_printf("test de a pour x [%x]\n", a, b);
	ft_printf("test de a pour X [%X]\n", a, b);
	ft_printf("test de a pour d \n", a);
	ft_printf("test de a pour o \n", a);
	ft_printf("test de a pour u \n", a);
	ft_printf("test de a pour x \n", a);
	ft_printf("test de a pour X \n", a);
	printf("test de a pour x [%#x]\n", d);
	ft_printf("test de a pour x [%#x]\n", d);
	printf("test de a pour x [%#5.x]\n", d);
	ft_printf("test de a pour x [%#5.x]\n", d);
	printf("test de a pour x [%#o]\n", d);
	ft_printf("test de a pour x [%#o]\n", d);
	printf("test de a pour x [%5.o]\n", d);
	ft_printf("test de a pour x [%5.o]\n", d);
	printf("test de a pour x [%#5.o]\n", d);
	ft_printf("test de a pour x [%#5.o]\n", d);
	printf("test de a pour x [%.o]\n", d);
	ft_printf("test de a pour x [%.o]\n", d);
	printf("test de a pour x [%.d]\n", 1);
	ft_printf("test de a pour x [%.d]\n", 1);
	printf("%   %\n", "test");
	ft_printf("%   %\n", "test");
	printf("[%010s]\n", NULL);
	printf("[%010.6s]\n", NULL);
	printf("[%010ls]\n", NULL);
	printf("[%10.5ls]\n", NULL);
	printf("[%#08x]\n", 42);
	ft_printf("[%#08x]\n", 42);
	printf("[%0+5d]\n", 42);
	ft_printf("[%0+5d]\n", 42);
	printf("[%0+5d]\n", -42);
	ft_printf("[%0+5d]\n", -42);
//	printf("[%s]\n", NULL);
	ft_printf("[%s]\n", NULL);
	printf("[%s] [%s]\n", NULL, "string");
	ft_printf("[%s] [%s]\n", NULL, "string");
	printf("llu est [%llu]\n", 4999999999);
	ft_printf("llu est [%llu]\n", 4999999999);
	printf("hU est [%hU]\n", 4294967296);
//	ft_printf("hU est [%hU]\n", 4294967296);
	printf("hhd est [%hhd]\n", -128);
	ft_printf("hhd est [%hhd]\n", -128);
	printf("lld est [%lld]\n", -9223372036854775808);
	printf("lld est [%lld]\n", -9223372036854775809);
	printf("03.2d est [%03.0d]\n", 1);
	ft_printf("03.2d est [%03.0d]\n", 1);
	printf("03.2d est [%3.2d]\n", 0);
	ft_printf("03.2d est [%3.2d]\n", 0);
	ft_printf("lld est [%lld]\n", e);
	ft_printf("jd est [%jd]\n", e);
/	ft_printf("[%s]\n", NULL);
//	ft_printf("[%.2c]\n", NULL);
	printf("[%]\n");
	ft_printf("[%]\n");
	printf("[%5+d]\n", 42);
	ft_printf("[%5+d]\n", 42);
	printf("[%5+d]\n", -42);
	ft_printf("[%5+d]\n", -42);
	printf("[%-5+d]\n", 42);
	ft_printf("[%-5+d]\n", 42);
	printf("[%-5+d]\n", -42);
	ft_printf("[%-5+d]\n", -42);
*/	//ft_printf("%####0000 33..1d", 256);
	printf("% Z %s", "test\n");
	ft_printf("% Z %s", "test\n");
	return (0);
}
